### ISSUE TITLE
KIP - Mining rewards in function of transactions

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-contracts-cpp#25]
Suppose that a miner decides to create blocks without transactions on it. The purpose to do that is to reduce resources in his node, so he preserves only the headers or take them from external nodes.

At the end this miner will mine, receive rewards, but he will not contribute to the blockchain by adding transactions. 

On bitcoin this is prevented by adding fees in the transactions. So, miners are incentivized to include transactions that contain more fees.

I propose to include the resources (or mana) in the arguments of the POW function and **give more rewards as more mana is consumed**. (To take into account for the mainnet as well if there are no incentives to include transactions in the blocks).

**Comment by mvandeberg** [comment]
This was not integrated in to the main net, but I feel still deserves a quick response as to why. If for no other reason than historical documentation.

There are a few problems if a block producer is incentivized in KOIN for including transactions that consume mana.

1. Inefficient transactions are prioritized. This creates a conflict of interest for DAPP developers to optimize their apps because an optimized DAPP is not prioritized by block producers.

2. It provides a path for users to convert Mana in to KOIN. A block producer can fill their block with transactions consuming all of their mana to get bonus rewards, essentially converting their spare mana in to more KOIN.

Even if the block producer was just rewarded with more mana, it would then allow a block producer to potentially go over 100% mana.
